### ISSUE TITLE
race condition in ResultSet.__iter__()

### ISSUE THREAD

**Issue by hrldcpr** [kennethreitz/records#13]
If you create two or more iterators over a ResultSet, then they consume `ResultSet._rows` together, meaning they all iterate over different rows. I.e. something like:
```python
rows = db.query('select * from active_users')
itera = iter(rows)
iterb = iter(rows)
print(next(itera))  # row 1
print(next(iterb))  # row 2
```

Of course, once all rows have been iterated over and fully cached, then iterators behave correctly, since they are independently iterating over the `ResultSet._all_rows` list, something like:
```python
rows = db.query('select * from active_users')
for row in rows: continue
itera = iter(rows)
iterb = iter(rows)
print(next(itera))  # row 1
print(next(iterb))  # row 1
```

Maybe this is intentional, but to me it seems confusing / not a standard iterator behavior. :bus:

**Comment by kennethreitz** [comment]
This was just fixed by https://github.com/kennethreitz/records/pull/22

Thanks for reporting!

**Comment by hrldcpr** [comment]
Thanks for #22, @mcdallas, it definitely fixed my two other issues. This issue isn't fixed though, there's still nothing stopping multiple iterators from ending up in the "consuming" part of the function, for example:
```python
rows = db.query('select * from active_users')
itera = iter(rows)
iterb = iter(rows)
print(next(itera))  # row 1, from the iterable
print(next(iterb))  # row 1, from the cache
print(next(iterb))  # row 2, from the iterable
print(next(itera))  # row 3, from the iterable (row 2 was skipped!)
```

I'm at a real computer this time so can do more than make issues; I'll make a pull request with a fix soon, but in the meantime this should probably be re-opened.

**Comment by hrldcpr** [comment]
Oh and there's a simpler way to test the bug with just one iterator, since the ResultSet itself is already a second iterator sort of…
```python
rows = db.query('select * from active_users')
it = iter(rows)
print(next(it))  # row 1
next(rows)
print(next(it))  # row 3
```
